#!/bin/sh

NPM_PACKAGE_VERSION=$(semver $(node -p -e "require('./package.json').version"))
GIT_TAG_VERSION=$(semver $(git describe --tags || echo "0.0.0"))

if [ $NPM_PACKAGE_VERSION != $GIT_TAG_VERSION ]; then
  echo "Error: NPM package version $NPM_PACKAGE_VERSION does not match the GIT tag version $GIT_TAG_VERSION"
  exit 1
fi

npm publish
