#!/bin/sh
set -e

cd "$(dirname "$0")/.."

./node_modules/.bin/http-server test/mock/app/ --silent &
HTTP_SERVER_PID=$!
trap "kill $HTTP_SERVER_PID 2> /dev/null" SIGINT SIGTERM EXIT

WDIO_CONFIG="./config/wdio.config.js"

if [ "$CI" = true ]; then
  WDIO_CONFIG="./config/wdio.config.ci.js"
fi

PARAMETERS=""

if [ "$1" != "" ]; then
  PARAMETERS="--spec $1"
fi

./node_modules/.bin/wdio $WDIO_CONFIG $PARAMETERS
