#!/bin/sh
set -e

cd "$(dirname "$0")/.."

scripts/cibuild

http-server test/mock/app/ --silent &
trap "trap - SIGTERM 2> /dev/null && kill -- -$$ 2> /dev/null" INT TERM EXIT

WDIO_CONFIG="./config/wdio.config.js"

if [ "$CI" = true ]; then
  WDIO_CONFIG="./config/wdio.config.ci.js"
fi

PARAMETERS=""

if [ "$1" != "" ]; then
  PARAMETERS="--spec $1"
fi

wdio $WDIO_CONFIG $PARAMETERS
